version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    volumes:
      - .:/go/src/sansara
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tty: true
    ports:
      - "8080:8080"